<#import "commons.ftl" as com>
<#import "classContent.ftl" as class>
package ${packageName};

/**
 * Generated by RIGD-Loxia Builder generator
 */
public<#if isAbstract()> abstract</#if> class ${builderClassName}<PARENT> <#if extendsBuilder()>extends ${extendedBuilderName}<PARENT> </#if>{
<@class.generateContent .data_model/>
}