package nl.loxia.builder.generator.ap.test;

/**
 * Generated by RIGD-Loxia Builder generator
 */
public class ListHandlingBuilder<PARENT> {
    private java.util.List<java.lang.String> values = new java.util.ArrayList<>();

    private PARENT parent;

    public ListHandlingBuilder() {
    }

    public ListHandlingBuilder(PARENT parent) {
        this.parent = parent;
    }

    /**
     * This replaces the collection currently present. Any previous calls to addValues are not saved.
     */
    public ListHandlingBuilder<PARENT> withValues(java.util.List<java.lang.String> values) {
        this.values = values;
        return this;
    }

    /**
     * this will add the supplied objects to the collection present. If an unmodifiable collection is set using {@link #withValues(java.util.List)} then an Exception can be thrown.
     */
    public ListHandlingBuilder<PARENT> addValues(Iterable<? extends String> values) {
        for (String v : values) {
            this.values.add(v);
        }
        return this;
    }

    /**
     * this will add the supplied objects to the collection present. If an unmodifiable collection is set using {@link #withValues(java.util.List)} then an Exception can be thrown.
     */
    public ListHandlingBuilder<PARENT> addValues(String... values) {
        for (String v : values) {
            this.values.add(v);
        }
        return this;
    }

    /**
     * returns the build object. For builder chaining use the {@link #end()} method to return the parent builder.
     */
    public ListHandling build() {
        ListHandling result = new ListHandling();
        result.getValues().addAll(values);
        return result;
    }

    /**
     * returns the parent builder if present, otherwise null is returned.
     */
    public PARENT end() {
        return parent;
    }

    public static ListHandlingBuilder<Void> copyOf(ListHandling bron) {
        if (bron == null) {
            return null;
        }
        ListHandlingBuilder<Void> builder = new ListHandlingBuilder<>();
        builder.values = new java.util.ArrayList<>(bron.getValues());
        return builder;
    }

    public static <T> ListHandlingBuilder<T> copyOf(ListHandling bron, T parentBuilder) {
        if (bron == null) {
            return null;
        }
        ListHandlingBuilder<T> builder = new ListHandlingBuilder<>(parentBuilder);
        builder.values = new java.util.ArrayList<>(bron.getValues());
        return builder;
    }
}