package nl.loxia.builder.generator.ap.test;

/**
 * Generated by RIGD-Loxia Builder generator
 */
public class ListHandlingBuilder<PARENT> {
    private java.util.List<String> values = new java.util.ArrayList<>();

    private PARENT parent;

    public ListHandlingBuilder() {
    }

    public ListHandlingBuilder(PARENT parent) {
        this.parent = parent;
    }

    public ListHandlingBuilder<PARENT> withValues(java.util.List<String> values) {
        this.values = values;
        return this;
    }

    public ListHandlingBuilder<PARENT> addValues(Iterable<? extends String> values) {
        for (String v : values) {
            this.values.add(v);
        }
        return this;
    }

    public ListHandlingBuilder<PARENT> addValues(String... values) {
        for (String v : values) {
            this.values.add(v);
        }
        return this;
    }

    public ListHandling build() {
        ListHandling result = new ListHandling();
        result.getValues().addAll(values);
        return result;
    }

    public PARENT end() {
        return parent;
    }

    public static ListHandlingBuilder<Void> copyOf(ListHandling bron) {
        if (bron == null) {
            return null;
        }
        ListHandlingBuilder<Void> builder = new ListHandlingBuilder<>();
        builder.values = new java.util.ArrayList<>(bron.getValues());
        return builder;
    }

    public static <T> ListHandlingBuilder<T> copyOf(ListHandling bron, T parentBuilder) {
        if (bron == null) {
            return null;
        }
        ListHandlingBuilder<T> builder = new ListHandlingBuilder<>(parentBuilder);
        builder.values = new java.util.ArrayList<>(bron.getValues());
        return builder;
    }
}
