package nl.loxia.builder.generator.ap.test.methodprefix;

/**
 * Generated by RIGD-Loxia Builder generator
 */
public class SetPrefixBuilder<PARENT> {
    private boolean booleanField;
    private String stringField;

    private PARENT parent;

    public SetPrefixBuilder() {
    }

    public SetPrefixBuilder(PARENT parent) {
        this.parent = parent;
    }

    public SetPrefixBuilder<PARENT> setBooleanField(boolean booleanField) {
        this.booleanField = booleanField;
        return this;
    }

    public SetPrefixBuilder<PARENT> setStringField(String stringField) {
        this.stringField = stringField;
        return this;
    }

    public SetPrefix build() {
        SetPrefix result = new SetPrefix(stringField);
        result.setBooleanField(booleanField);
        return result;
    }

    public PARENT end() {
        return parent;
    }

    public static SetPrefixBuilder<Void> copyOf(SetPrefix bron) {
        if (bron == null) {
            return null;
        }
        SetPrefixBuilder<Void> builder = new SetPrefixBuilder<>();
        builder.booleanField = bron.getBooleanField();
        builder.stringField = bron.getStringField();
        return builder;
    }

    public static <T> SetPrefixBuilder<T> copyOf(SetPrefix bron, T parentBuilder) {
        if (bron == null) {
            return null;
        }
        SetPrefixBuilder<T> builder = new SetPrefixBuilder<>(parentBuilder);
        builder.booleanField = bron.getBooleanField();
        builder.stringField = bron.getStringField();
        return builder;
    }
}
