package nl.loxia.builder.generator.ap.test.methodprefix;

/**
 * Generated by RIGD-Loxia Builder generator
 */
public class SetPrefixBuilder<PARENT> {
    private boolean booleanField;
    private String stringField;

    private PARENT parent;

    public SetPrefixBuilder() {
    }

    public SetPrefixBuilder(PARENT parent) {
        this.parent = parent;
    }

    public SetPrefixBuilder<PARENT> setBooleanField(boolean booleanField) {
        this.booleanField = booleanField;
        return this;
    }

    public SetPrefixBuilder<PARENT> setStringField(String stringField) {
        this.stringField = stringField;
        return this;
    }

    /**
     * returns the build object. For builder chaining use the {@link #end()} method to return the parent builder.
     */
    public SetPrefix build() {
        java.util.List<String> missingRequiredFields = new java.util.ArrayList<>();
        if (stringField == null) {
            missingRequiredFields.add("stringField");
        }
        if (!missingRequiredFields.isEmpty()) {
            throw new nl.loxia.builder.generator.annotations.BuilderValidationException("The following required fields are not set: "
                      + missingRequiredFields.stream().collect(java.util.stream.Collectors.joining(",")));
        }
        SetPrefix result = new SetPrefix(stringField);
        result.setBooleanField(booleanField);
        return result;
    }

    /**
     * returns the parent builder if present, otherwise null is returned.
     */
    public PARENT end() {
        return parent;
    }

    public static SetPrefixBuilder<Void> copyOf(SetPrefix bron) {
        if (bron == null) {
            return null;
        }
        SetPrefixBuilder<Void> builder = new SetPrefixBuilder<>();
        builder.booleanField = bron.getBooleanField();
        builder.stringField = bron.getStringField();
        return builder;
    }

    public static <T> SetPrefixBuilder<T> copyOf(SetPrefix bron, T parentBuilder) {
        if (bron == null) {
            return null;
        }
        SetPrefixBuilder<T> builder = new SetPrefixBuilder<>(parentBuilder);
        builder.booleanField = bron.getBooleanField();
        builder.stringField = bron.getStringField();
        return builder;
    }
}