package nl.loxia.builder.generator.ap.test.methodprefix;

/**
 * Generated by RIGD-Loxia Builder generator
 */
public class SimpleClassMixedBuilder<PARENT> {
    private boolean booleanField;
    private String stringField;

    private PARENT parent;

    public SimpleClassMixedBuilder() {
    }

    public SimpleClassMixedBuilder(PARENT parent) {
        this.parent = parent;
    }

    public SimpleClassMixedBuilder<PARENT> witherBooleanField(boolean booleanField) {
        this.booleanField = booleanField;
        return this;
    }

    public SimpleClassMixedBuilder<PARENT> witherStringField(String stringField) {
        this.stringField = stringField;
        return this;
    }

    /**
     * returns the build object. For builder chaining use the {@link #end()} method to return the parent builder.
     */
    public SimpleClassMixed build() {
        java.util.List<String> missingRequiredFields = new java.util.ArrayList<>();
        if (stringField == null) {
            missingRequiredFields.add("stringField");
        }
        if (!missingRequiredFields.isEmpty()) {
            throw new nl.loxia.builder.generator.annotations.BuilderValidationException("The following required fields are not set: "
                      + missingRequiredFields.stream().collect(java.util.stream.Collectors.joining(",")));
        }
        SimpleClassMixed result = new SimpleClassMixed(stringField);
        result.setBooleanField(booleanField);
        return result;
    }

    /**
     * returns the parent builder if present, otherwise null is returned.
     */
    public PARENT end() {
        return parent;
    }

    public static SimpleClassMixedBuilder<Void> copyOf(SimpleClassMixed bron) {
        if (bron == null) {
            return null;
        }
        SimpleClassMixedBuilder<Void> builder = new SimpleClassMixedBuilder<>();
        builder.booleanField = bron.getBooleanField();
        builder.stringField = bron.getStringField();
        return builder;
    }

    public static <T> SimpleClassMixedBuilder<T> copyOf(SimpleClassMixed bron, T parentBuilder) {
        if (bron == null) {
            return null;
        }
        SimpleClassMixedBuilder<T> builder = new SimpleClassMixedBuilder<>(parentBuilder);
        builder.booleanField = bron.getBooleanField();
        builder.stringField = bron.getStringField();
        return builder;
    }
}
